In [1]:
import pandas as pd

### Импорт датасета и создание датафрейма

In [2]:
# Датасет отзывов на Яндекс Картах https://github.com/yandex/geo-reviews-dataset-2023.git
# Путь к файлу
file_path = '/home/jupyter/datasphere/project/final_project/geo-reviews-dataset-2023.tskv'

# Создание списка для хранения распарсенных строк
parsed_rows = []

# Открытие файла и преобразование датасета к нормальной таблице 
with open(file_path, 'r', encoding='utf8') as file:
    for line in file:
        row_dict = {}
        elements = line.strip().split('\t')
        for element in elements:
            if '=' in element:
                key, value = element.split('=', 1)
                row_dict[key] = value
        parsed_rows.append(row_dict)

# Создание датафрейма
df = pd.DataFrame(parsed_rows)
df

                                                  address  ...                                               text
0       Екатеринбург, ул. Московская / ул. Волгоградск...  ...  Московский квартал 2.\nШумно : летом по ночам ...
1       Московская область, Электросталь, проспект Лен...  ...  Замечательная сеть магазинов в общем, хороший ...
2       Краснодар, Прикубанский внутригородской округ,...  ...  Не знаю смутят ли кого-то данные правила, но я...
3        Санкт-Петербург, проспект Энгельса, 111, корп. 1  ...  Хорошие условия аренды. \nДружелюбный персонал...
4                       Тверь, Волоколамский проспект, 39  ...  Топ мастер Ангелина топ во всех смыслах ) Немн...
...                                                   ...  ...                                                ...
499995  Москва, Южный административный округ, район Би...  ...  Охрана кривая но добрая, двери не закрываются ...
499996  Москва, Южный административный округ, район Би...  ...  По сравнению со многими современными платформа...
499997           Новосибирск, Коммунистическая улица, 48А  ...  Приятная атмосфера, прекрасное вино, волшебная...
499998          Астраханская область, Харабалинский район  ...  Был с семьёй 13.06.23 Отличное место. Рекоменд...
499999          Астраханская область, Харабалинский район  ...  Отличные декорации... Вблизи тяп-ляп,а на фото...

[500000 rows x 5 columns]

### Формирмирование данных для анализа отзывов на гостиницы

In [3]:
# Разделим строки на отдельные рубрики
df['rubrics'] = df['rubrics'].str.split(';')
df_split_rubrics = df.explode('rubrics')

df_split_rubrics

                                                  address  ...                                               text
0       Екатеринбург, ул. Московская / ул. Волгоградск...  ...  Московский квартал 2.\nШумно : летом по ночам ...
1       Московская область, Электросталь, проспект Лен...  ...  Замечательная сеть магазинов в общем, хороший ...
1       Московская область, Электросталь, проспект Лен...  ...  Замечательная сеть магазинов в общем, хороший ...
1       Московская область, Электросталь, проспект Лен...  ...  Замечательная сеть магазинов в общем, хороший ...
2       Краснодар, Прикубанский внутригородской округ,...  ...  Не знаю смутят ли кого-то данные правила, но я...
...                                                   ...  ...                                                ...
499995  Москва, Южный административный округ, район Би...  ...  Охрана кривая но добрая, двери не закрываются ...
499996  Москва, Южный административный округ, район Би...  ...  По сравнению со многими современными платформа...
499997           Новосибирск, Коммунистическая улица, 48А  ...  Приятная атмосфера, прекрасное вино, волшебная...
499998          Астраханская область, Харабалинский район  ...  Был с семьёй 13.06.23 Отличное место. Рекоменд...
499999          Астраханская область, Харабалинский район  ...  Отличные декорации... Вблизи тяп-ляп,а на фото...

[929973 rows x 5 columns]

In [4]:
# Подсчитаем количество отзывов в каждой рубрике и выведем TOP 10 рубрик
df_split_rubrics['rubrics'].value_counts().head(10)

Кафе                     58496
Ресторан                 56761
Гостиница                43133
Магазин продуктов        21346
Супермаркет              19746
Бар, паб                 19238
Салон красоты            17910
Быстрое питание          16859
Доставка еды и обедов    14394
Ногтевая студия          11649
Name: rubrics, dtype: int64

In [5]:
# Выберем отзывы c рубрикой "Гостиница"
df_hotels_reviews = df_split_rubrics.query("rubrics == 'Гостиница'")
df_hotels_reviews

                                                  address  ...                                               text
16      Алтайский край, особая экономическая зона тури...  ...  Очень крутые экскурсии. Обязательно приедем ещ...
48      Севастополь, Балаклавский муниципальный округ,...  ...  Понравилось все! Гостеприимство, чистота, спок...
77      Свердловская область, Нижний Тагил, улица Окун...  ...  Моментальное бронирование, быстрая регистрация...
105         Ростов-на-Дону, проспект 40-летия Победы, 198  ...  Хорошей отель. Девушка на ресепшен очень добро...
106         Ростов-на-Дону, проспект 40-летия Победы, 198  ...  Гостиница понравилась. Отличное сочетание цены...
...                                                   ...  ...                                                ...
499956                           Тула, Советская улица, 3  ...  Отличный отель, есть все необходимое. Халат, з...
499957                           Тула, Советская улица, 3  ...  Красиво, всё новое, хорошие номера. Минусы: пл...
499958                           Тула, Советская улица, 3  ...  В отеле остановились по дороге домой из Москвы...
499959                           Тула, Советская улица, 3  ...  4 только из-за того что по утрам нет горячей в...
499960                           Тула, Советская улица, 3  ...  Отель хороший. Чисто и комфортно. Брал с завтр...

[43133 rows x 5 columns]

In [6]:
# Удалим колонки rubrics, address и name_ru из датафрейма, так как они нам не понадобятся для анализа
df_hotels_reviews = df_hotels_reviews.drop(columns=['rubrics', 'address', 'name_ru'])
df_hotels_reviews

       rating                                               text
16         5.  Очень крутые экскурсии. Обязательно приедем ещ...
48         5.  Понравилось все! Гостеприимство, чистота, спок...
77         5.  Моментальное бронирование, быстрая регистрация...
105        5.  Хорошей отель. Девушка на ресепшен очень добро...
106        5.  Гостиница понравилась. Отличное сочетание цены...
...       ...                                                ...
499956     5.  Отличный отель, есть все необходимое. Халат, з...
499957     4.  Красиво, всё новое, хорошие номера. Минусы: пл...
499958     5.  В отеле остановились по дороге домой из Москвы...
499959     4.  4 только из-за того что по утрам нет горячей в...
499960     3.  Отель хороший. Чисто и комфортно. Брал с завтр...

[43133 rows x 2 columns]

In [7]:
# Проверим типы данных в датафрейме
df_hotels_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43133 entries, 16 to 499960
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rating  43133 non-null  object
 1   text    43133 non-null  object
dtypes: object(2)
memory usage: 1010.9+ KB

In [8]:
# Преобразуем тип колонки rating из строки в целое число
df_hotels_reviews['rating'] = df_hotels_reviews['rating'].astype(float).astype(int)
df_hotels_reviews

        rating                                               text
16           5  Очень крутые экскурсии. Обязательно приедем ещ...
48           5  Понравилось все! Гостеприимство, чистота, спок...
77           5  Моментальное бронирование, быстрая регистрация...
105          5  Хорошей отель. Девушка на ресепшен очень добро...
106          5  Гостиница понравилась. Отличное сочетание цены...
...        ...                                                ...
499956       5  Отличный отель, есть все необходимое. Халат, з...
499957       4  Красиво, всё новое, хорошие номера. Минусы: пл...
499958       5  В отеле остановились по дороге домой из Москвы...
499959       4  4 только из-за того что по утрам нет горячей в...
499960       3  Отель хороший. Чисто и комфортно. Брал с завтр...

[43133 rows x 2 columns]

In [9]:
# Подсчитаем количество отзывов в разрезе рейтинга
df_hotels_reviews['rating'].value_counts()

5    31980
4     5933
3     2577
1     1511
2     1108
0       24
Name: rating, dtype: int64

In [10]:
# Удалим отзывы с рейтингом = 0
df_hotels_reviews = df_hotels_reviews[df_hotels_reviews['rating'] != 0]
df_hotels_reviews['rating'].value_counts()

5    31980
4     5933
3     2577
1     1511
2     1108
Name: rating, dtype: int64

In [11]:
# Подсчитаем количество отзывов, где количество символов меньше 10
short = (df_hotels_reviews['text'].str.len() < 10).sum()
print(f"Количество отзывов, где количество символов меньше 10: {short}")

Количество отзывов, где количество символов меньше 10: 1

In [12]:
# Удалим отзывы, где количество символов меньше 10
df_hotels_reviews = df_hotels_reviews[df_hotels_reviews['text'].str.len() > 10]

In [13]:
# Провериим датафрейм на наличие пропущенных значений в каждом столбце
print("Количество пропущенных значений в каждом столбце:")
df_hotels_reviews.isnull().sum()

Количество пропущенных значений в каждом столбце:

rating    0
text      0
dtype: int64

In [14]:
# Проверим датафрейм на дубликаты строк
duplicates = df_hotels_reviews.duplicated().sum()
print(f"Количество дублирующихся строк: {duplicates}")

Количество дублирующихся строк: 5

In [15]:
# Удалим дубликаты строк
df_hotels_reviews = df_hotels_reviews.drop_duplicates()

In [16]:
df_hotels_reviews

        rating                                               text
16           5  Очень крутые экскурсии. Обязательно приедем ещ...
48           5  Понравилось все! Гостеприимство, чистота, спок...
77           5  Моментальное бронирование, быстрая регистрация...
105          5  Хорошей отель. Девушка на ресепшен очень добро...
106          5  Гостиница понравилась. Отличное сочетание цены...
...        ...                                                ...
499956       5  Отличный отель, есть все необходимое. Халат, з...
499957       4  Красиво, всё новое, хорошие номера. Минусы: пл...
499958       5  В отеле остановились по дороге домой из Москвы...
499959       4  4 только из-за того что по утрам нет горячей в...
499960       3  Отель хороший. Чисто и комфортно. Брал с завтр...

[43102 rows x 2 columns]

In [18]:
# Сохраним подготовленный датасет в файл
df_hotels_reviews.to_csv('hotels_reviews_dataset.csv', index=False)